In [ ]:
# task 1
import pandas as pd
import numpy as np

In [ ]:
# Taking random values with 4 features and 4 observations
data = np.random.rand(4, 4)
# Creating the DataFrame
df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])
df

   Feature1  Feature2  Feature3  Feature4
0  0.562221  0.373657  0.290807  0.156231
1  0.891024  0.048213  0.169161  0.055350
2  0.674506  0.401030  0.272168  0.227856
3  0.971079  0.171928  0.956017  0.963197

In [ ]:
# Task 2
# Renaming the columns
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.562221        0.373657        0.290807        0.156231
1        0.891024        0.048213        0.169161        0.055350
2        0.674506        0.401030        0.272168        0.227856
3        0.971079        0.171928        0.956017        0.963197

In [ ]:
# Task 3
# Descriptive Statistics
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.774707        0.248707        0.422038        0.350658
std          0.189105        0.168234        0.359983        0.414445
min          0.562221        0.048213        0.169161        0.055350
25%          0.646435        0.140999        0.246416        0.131010
50%          0.782765        0.272793        0.281487        0.192043
75%          0.911038        0.380500        0.457109        0.411691
max          0.971079        0.401030        0.956017        0.963197

In [ ]:
# Task 4
# Check for null values in df
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [ ]:
# Find the datatype of columns
df.dtypes

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
# Task 5
# Display Random value 2 columns with location method
df.loc[:,'Random value 2']

0    0.373657
1    0.048213
2    0.401030
3    0.171928
Name: Random value 2, dtype: float64

In [ ]:
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.562221        0.373657        0.290807        0.156231
1        0.891024        0.048213        0.169161        0.055350
2        0.674506        0.401030        0.272168        0.227856
3        0.971079        0.171928        0.956017        0.963197

In [ ]:
# Display Random value 3 columns with location method
df.loc[:,'Random value 3']

0    0.290807
1    0.169161
2    0.272168
3    0.956017
Name: Random value 3, dtype: float64

In [ ]:
# Display Random value 2 columns with index location method
df.iloc[:,1]

0    0.373657
1    0.048213
2    0.401030
3    0.171928
Name: Random value 2, dtype: float64

In [ ]:
# Display Random value 3 columns with index location method
df.iloc[:,2]

0    0.290807
1    0.169161
2    0.272168
3    0.956017
Name: Random value 3, dtype: float64